baseURL = 'https://cmart-seq.github.io/goodbees.github.io'
languageCode = 'en-us'
title = 'will you raise good bees'
theme = 'PaperMod'
publishDir = "docs"
pygmentsUseClasses = false
pygmentsCodefences = true

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
tabWidth = 2
style = "dracula"

[markup.goldmark.renderer]
unsafe = true
